name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker with Google Cloud
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > /tmp/gcloud-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcloud-key.json
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev
          rm /tmp/gcloud-key.json

      - name: Build Docker image
        run: |
          docker build -t southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/apt-1006-back-repository/nest .

      - name: Push Docker image to Google Artifact Registry
        run: |
          docker push southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/apt-1006-back-repository/nest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy apt-1006-back --image southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/apt-1006-back-repository/nest --region southamerica-east1
